import { configStore } from '../config/store.js';

class DiscordService {
  getWebhookUrl() {
    const config = configStore.get('discord');
    return config?.webhookUrl || null;
  }

  isConfigured() {
    const webhookUrl = this.getWebhookUrl();
    return !!(webhookUrl && webhookUrl.includes('discord.com/api/webhooks'));
  }

  async sendMessage(content, options = {}) {
    const webhookUrl = this.getWebhookUrl();
    
    if (!webhookUrl) {
      throw new Error('Discord webhook URL not configured');
    }

    const payload = {
      content: content.substring(0, 2000),
      username: options.username || 'File Assistant',
      avatar_url: options.avatarUrl || 'https://cdn-icons-png.flaticon.com/512/2593/2593635.png'
    };

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Discord API error: ${response.status} - ${error}`);
    }

    return { success: true };
  }

  async sendEmbed(embed, options = {}) {
    const webhookUrl = this.getWebhookUrl();
    
    if (!webhookUrl) {
      throw new Error('Discord webhook URL not configured');
    }

    const payload = {
      username: options.username || 'File Assistant',
      avatar_url: options.avatarUrl || 'https://cdn-icons-png.flaticon.com/512/2593/2593635.png',
      embeds: [embed]
    };

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Discord API error: ${response.status} - ${error}`);
    }

    return { success: true };
  }

  async sendCatchUpSummary(summary, sources = []) {
    const embed = {
      title: '📬 Message Catch-Up Summary',
      description: summary.substring(0, 4096),
      color: 0x3b82f6,
      fields: [],
      footer: {
        text: `Generated by File Assistant • ${new Date().toLocaleString()}`
      },
      timestamp: new Date().toISOString()
    };

    if (sources.length > 0) {
      const sourcesList = sources.map(s => {
        const icon = s.source === 'teams' ? '💼' : '💬';
        return `${icon} **${s.channelName}** (${s.messageCount} messages)`;
      }).join('\n');

      embed.fields.push({
        name: '📊 Sources',
        value: sourcesList.substring(0, 1024),
        inline: false
      });
    }

    return this.sendEmbed(embed);
  }

  async sendFileNotification(files) {
    if (files.length === 0) return { success: true };

    const fileList = files.slice(0, 10).map(f => {
      const icon = f.source === 'teams' ? '💼' : '💬';
      return `${icon} **${f.name}**`;
    }).join('\n');

    const embed = {
      title: `📁 ${files.length} New File${files.length > 1 ? 's' : ''} Downloaded`,
      description: fileList,
      color: 0x22c55e,
      footer: {
        text: `File Assistant • ${new Date().toLocaleString()}`
      }
    };

    if (files.length > 10) {
      embed.description += `\n\n*...and ${files.length - 10} more*`;
    }

    return this.sendEmbed(embed);
  }

  async testWebhook() {
    const embed = {
      title: '✅ Webhook Test Successful',
      description: 'Your Discord webhook is configured correctly. You will receive message summaries and file notifications here.',
      color: 0x22c55e,
      footer: {
        text: 'File Assistant'
      }
    };

    return this.sendEmbed(embed);
  }
}

export const discordService = new DiscordService();
